kind: pipeline
type: docker
name: default

steps:
- name: package
  image: plugins/docker
  settings:
    registry: 192.168.56.1:5000
    repo: 192.168.56.1:5000/devprivops-ui
    tags: latest
    dockerfile: Dockerfile
    insecure: true
trigger:
  event:
    - push